Feat/workout view
Swift-Coding-Club/MoveYourBody pull request #38
Opened 2023-03-30 09:39 UTC by KSYong

2023-03-30 15:09 UTC, thisisthewa2 commented on MoveYourBody/View/WorkoutSettings/WorkoutSettingsView.swift
> +                                if settings.selectUpperBody == true && settings.selectLowerBody == true {
저 대신 변수명을 직관적으로 바꿔주셨군요, 감사합니다.

2023-03-30 15:16 UTC, thisisthewa2 commented on MoveYourBody/Utilities/View+Extensions.swift
> +    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
어떤 경우에 사용되는 지 알 수 있을까요? 조건에 따라 transform(self)를 하는 이유를 잘 모르겠습니다.

2023-03-30 15:18 UTC, thisisthewa2 requested changes

2023-03-30 15:18 UTC, thisisthewa2 commented on MoveYourBody/View/WorkoutSettings/WorkoutSettingsView.swift
> +                                settings.selectFiveMinutes.toggle()
제가 한 부분과 수정 위치가 같아서 충돌이 날 것 같아, 승용님께서 머지 완료하시면 제가 다시 풀받고 수정해 다시 풀리퀘 올리겠습니다.

2023-04-01 09:47 UTC, KSYong commented on MoveYourBody/Utilities/View+Extensions.swift
> +    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
넵 이 코드는 View에 extension을 적용하여 추가 함수를 구현해 주었는데요, SwiftUI에서 뷰 모디파이어를 적용할 때 조건에 따라 적용하고 싶을 때가 있는데, 그 때 사용합니다! 예를 들어 Text("Hi")에 .font(.largeTitle)이라는 모디파이어를 isLarge라는 변수가 true일 때만 사용하고 싶을 때가 있을 텐데요, 그럴 때 사용하게 됩니다!

2023-04-01 09:49 UTC, KSYong commented on MoveYourBody/Utilities/View+Extensions.swift
> +    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
![Uploading Screenshot 2023-04-01 at 6.49.02 PM.png…]()

2023-04-01 09:50 UTC, KSYong commented on MoveYourBody/Utilities/View+Extensions.swift
> +    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
<img width="595" alt="Screenshot 2023-04-01 at 6 49 02 PM" src="https://user-images.githubusercontent.com/22342277/229279033-c5acda3e-e01e-4bb2-b55e-fe9d44528b03.png">

2023-04-01 09:51 UTC, KSYong commented on MoveYourBody/Utilities/View+Extensions.swift
> +    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
위 예시와 같이 사용하게 됩니다!

2023-04-01 09:51 UTC, KSYong commented on MoveYourBody/View/WorkoutSettings/WorkoutSettingsView.swift
> +                                settings.selectFiveMinutes.toggle()
넵 제가 변수명을 수정해서 충돌이 생겼군요 ㅠ 확인하였습니다!

2023-04-07 03:06 UTC, thisisthewa2 commented on MoveYourBody/Utilities/View+Extensions.swift
> +    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
그렇군요 친절한 설명 덕분에 이해했습니다!

2023-04-07 03:08 UTC, merged